// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Microservices.IoT.Data.Models
{
    public partial class EVENT
    {
        [Key]
        public int ID { get; set; }
        public int TypeID { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime From { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? To { get; set; }
        public int FridgeID { get; set; }

        [ForeignKey("FridgeID")]
        [InverseProperty("EVENT")]
        public virtual FRIDGE Fridge { get; set; }
        [ForeignKey("TypeID")]
        [InverseProperty("EVENT")]
        public virtual EVENT_TYPE Type { get; set; }
    }
}