// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Microservices.IoT.Data.Models
{
    public partial class FOOD_TYPE
    {
        public FOOD_TYPE()
        {
            FOOD = new HashSet<FOOD>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        public double Density { get; set; }
        public bool ImmutableVolumeHint { get; set; }
        public int HealthRatingID { get; set; }

        [ForeignKey("HealthRatingID")]
        [InverseProperty("FOOD_TYPE")]
        public virtual FOOD_HEALTH_RATING HealthRating { get; set; }
        [InverseProperty("Type")]
        public virtual ICollection<FOOD> FOOD { get; set; }
    }
}