// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Microservices.IoT.Data.Models
{
    public partial class FOOD
    {
        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        [StringLength(100)]
        public string Producer { get; set; }
        public int TypeID { get; set; }
        public bool Open { get; set; }
        public int InitialWeightGrams { get; set; }
        public int CurrentWeightGrams { get; set; }
        public bool ImmutableVolume { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ExpirationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        public int? FridgeID { get; set; }

        [ForeignKey("FridgeID")]
        [InverseProperty("FOOD")]
        public virtual FRIDGE Fridge { get; set; }
        [ForeignKey("TypeID")]
        [InverseProperty("FOOD")]
        public virtual FOOD_TYPE Type { get; set; }
    }
}