// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Microservices.IoT.Data.Models
{
    [Index("Name", Name = "IX_FRIDGE_NAME", IsUnique = true)]
    public partial class FRIDGE
    {
        public FRIDGE()
        {
            EVENT = new HashSet<EVENT>();
            FOOD = new HashSet<FOOD>();
        }

        [Key]
        public int ID { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Brand { get; set; }
        public int TypeID { get; set; }
        public int DesignedMaximalPowerConsumptionWatts { get; set; }
        public int CapacityLiters { get; set; }
        public double ConfiguredOperatingTemperatureDegrees { get; set; }
        public double CurrentTemperatureDegrees { get; set; }
        public int CurrentPowerConsumptionWatts { get; set; }
        public bool IsOpen { get; set; }
        public int DoorOpenPeriodSecondsForWarning { get; set; }
        public double DegreesOffsetForTemperatureWarning { get; set; }

        [ForeignKey("TypeID")]
        [InverseProperty("FRIDGE")]
        public virtual FRIDGE_TYPE Type { get; set; }
        [InverseProperty("Fridge")]
        public virtual ICollection<EVENT> EVENT { get; set; }
        [InverseProperty("Fridge")]
        public virtual ICollection<FOOD> FOOD { get; set; }
    }
}